### PR TITLE
RTS: address warnings and enable -Werror

### PR DESCRIPTION
**Pull request by ckoparkar**
Following #246, this PR cleans up warnings in the RTS.

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Terrific!

**Comment by ulysses4ever** [comment]
Interestingly, it now fails for me in the nix-shell:

```
[nix-shell:/mnt/data/artem/Dev/gibbon/gibbon-2]$ $g --run --packed --parallel sumtree.hs
codegen: C RTS could not be compiled: gcc -Wall -Wextra -Wpedantic -Wshadow -Werror -std=gnu11 -flto -D_GIBBON_VERBOSITY=1 -D_GIBBON_GENGC=0 -fcilkplus -D_GIBBON_PARALLEL -D_GIBBON_EAGER_PROMOTION=1 -D_GIBBON_SIMPLE_WRITE_BARRIER=0 -O3  -flto  -c -o /mnt/data/artem/Dev/gibbon/gibbon-2/gibbon-rts/rts-c/gibbon_rts.o /mnt/data/artem/Dev/gibbon/gibbon-2/gibbon-rts/rts-c/gibbon_rts.c

In file included from /mnt/data/artem/Dev/gibbon/gibbon-2/gibbon-rts/rts-c/gibbon_rts.c:4:0:
/mnt/data/artem/Dev/gibbon/gibbon-2/gibbon-rts/rts-c/gibbon_rts.h: In function 'gib_get_thread_id':
/mnt/data/artem/Dev/gibbon/gibbon-2/gibbon-rts/rts-c/gibbon_rts.h:358:12: error: implicit declaration of function '__cilkrts_get_worker_number' [-Werror=implicit-function-declaration]
     return __cilkrts_get_worker_number();
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I can fix it by adding the cilk `#include` to the `gibbon_rts.h` but I wonder why it fails only for me...

**Comment by ckoparkar** [comment]
I suppose no one built with `--parallel` after this commit. Some of the tests should have triggered this?

**Comment by ulysses4ever** [comment]
Right, I'm surprised none of the tests caught it. I hope to look closer into tests...

**Comment by ulysses4ever** [comment]
I looked into `test-gibbon-examples.yaml`, and it only has three `--parallel` examples, e.g.

https://github.com/iu-parfunc/gibbon/blob/d59464da0f54399d01038a93cee49072acb4e749/gibbon-compiler/tests/test-gibbon-examples.yaml#L465-L471

All of them are skipped! Because... wait for it!

> Cilk not supported on newer GCCs.

It would be great to figure something out about Cilk!

**Pull request merged**
