### PR TITLE
codegen: avoid generating two unconditional returns in C code

### PR DESCRIPTION
**Pull request by ulysses4ever**

### CODE REVIEW

**Comment by ulysses4ever** [comment]
I did take a look at the C code, yes. But not at any functions other than `main`. I assumed that this `return 0` only ever gets into `main` (that's what I observed in simple programs). After you asked, I'm not sure anymore. I hoped that the test suite is extensive enough to catch any issue that comes around due to this change. But that's an optimistic view and not necessarily correct...

Do you have a gibbon program in mind that would trigger this branch other than for generating an exit code in `main`? I had a couple of quick shots around empty cases but didn't manage to get anything compilable. I also tried to see in the code how `RetValsT []` can come into being and didn't quickly find anything other than specifically lowering the `main` expression, which, if it's indeed the only possibility how you can end up with an empty list in this constructor, would fit my approach just fine. But again, I don't have 100% confidence that `RetValsT []` can only be created for the `main` expression.

I guess, I'll transform this into a draft PR while we're investigating.

**Comment by ulysses4ever** [comment]
I didn't want to occupy more of your time!

I was thinking that a proper way to fix it may be to add a constructor to `Tail` called `EndOfMain` or something like that. I think currently `RetValsT []` represents exactly that but with a separate constructor it would be more clear. Also, `RetValsT []` as the end of `main` is currently added here:

https://github.com/iu-parfunc/gibbon/blob/efd6b60cb6b5f56082c39a8ab351767fe9d5d742/gibbon-compiler/src/Gibbon/Passes/Lower.hs#L315-L327

And this function is only used for `mainExpr`:

https://github.com/iu-parfunc/gibbon/blob/efd6b60cb6b5f56082c39a8ab351767fe9d5d742/gibbon-compiler/src/Gibbon/Passes/Lower.hs#L370-L373

So, if `addPrintToTail` were to add `EndOfMain` instead, and the codegen did the right thing for this constructor, then, I hope, my initial concern about two returns in `main` (C level) would be solved and your concern about disturbing codegen for functions other than `main` would also be addressed...

I haven't analyzed how disrupting is adding a constructor to `Tail`. My mild worry is that it'd require updating a good bunch of case expressions...

**Comment by ckoparkar** [comment]
@ulysses4ever I like the explicit `EndOfMain` marker, but it would require updating case expressions like you said. One quick thing I'd check is what happens to functions that return a unit tuple after this patch:

```
unit :: ()
unit = ()
``` 

I think `()` will be `ProdTy []` until L3, but I'm forgetting how we lower this to L4. This may be another source of `RetVals []`.

**Comment by ulysses4ever** [comment]
@ckoparkar thanks a lot for chiming in! You were absolutely right about `unit`: it does produce the same AST that I tried to highjack for `main` only. I now added `EndOfMain`. It required updating several `case`s but was quite easy.

**Comment by ckoparkar** [comment]
Super!

**Comment by ulysses4ever** [comment]
I take it as an approval and merge then :-)

@vidsinghal I did several experiments and eyeballed generated C and it looked as expected. So I'm going to merge now to move on, but we can always revisit.

**Pull request merged**
